services:
  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/

  mqtt:
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mqtt_config:/mosquitto/config:rw    
      - ./mqtt_data:/mosquitto/data:rw
      - ./mqtt_log:/mosquitto/log:rw

volumes:
  postgres_data:
  mqtt_config:
  mqtt_data:
  mqtt_log:
